Add Stepup API configuration to docker
OpenConext/OpenConext-devconf pull request #2
Opened 2023-07-05 11:08 UTC by rubencatshoek

Originally the configuration was done in the Stepup API project, but we decided that it would be better to add it to the devconf as well. Mostly because the API uses the Middleware.

This PR is based on the PR created by Dan, to which I added the docker configuration for the Stepup API.

2023-07-05 11:54 UTC, quartje requested changes

2023-07-05 11:54 UTC, quartje commented on stepup/api/docker-compose.override.yml
> +  api:
Let's rename this to stepupapi (as the loadbalancer will then autodiscover it)

2023-07-05 11:54 UTC, quartje commented on stepup/docker-compose.yml
> +  api:
Same: Please rename to stepupapi

2023-11-08 07:47 UTC, MKodde commented
Closing this for now. Given the low complexity of adding this project we can add it at a later stage.

2023-11-08 07:47 UTC, closed without merging